[package]
name = "Traglast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.4"
plotters = "0.3.4"
itertools = "0.10.5"
numerals = "0.1"